# -*- coding: utf-8 -*-
"""Breast Cancer Detection using TensorFlow 2.0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zeZo5L5Cf9lm8HyR9yWX8SiQQmTwEgON
"""

import tensorflow as tf

#Load the data
from sklearn.datasets import load_breast_cancer

data=load_breast_cancer()

type(data)

data.keys()

data.data.shape

data.target

data.target_names

data.target.shape

data.feature_names



"""Train and test data"""

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(data.data,data.target,test_size=0.20)

N,D=X_train.shape

"""Scale the data"""

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

#build the model
model=tf.keras.models.Sequential([

              tf.keras.layers.Input(shape=(D,)) ,
              tf.keras.layers.Dense(1,activation='sigmoid')                 
                                 

    
    
])

model.compile(optimizer="adam",loss='binary_crossentropy',metrics=['accuracy'])

num_of_epochs=150
r=model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=num_of_epochs)

model.evaluate(X_train,Y_train)
model.evaluate(X_test,Y_test)

